# Generated by Django 4.1.2 on 2022-11-13 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('card_type', models.CharField(choices=[('MasterCard', 'Mastercard'), ('Visa', 'Visa')], default='MasterCard', max_length=10)),
                ('ccv', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(default='Dermatology', max_length=200)),
                ('specialize', models.CharField(default='Level II', max_length=50)),
                ('specialist', models.CharField(choices=[('Family medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Pediatrician', 'Pediatrician'), ('Obstetricians/gynecologist (OBGYNs)', 'Obstetricians Gynecologist'), ('Cardiologist', 'Cardiologist'), ('Oncologist', 'Oncologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Infectious disease', 'Infectious Disease'), ('Nephrologist', 'Nephrologist'), ('Endocrinologist', 'Endocrinologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Dermatologist', 'Dermatologist'), ('Psychiatrist', 'Psychiatrist'), ('Neurologist', 'Neurologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Surgeon', 'Surgeon'), ('Physician executive', 'Physician Executive')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('line_total', models.FloatField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=30)),
                ('usage', models.CharField(blank=True, max_length=100)),
                ('origin_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('dose_per_day', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, default=37, null=True)),
                ('blood_pressure', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.CharField(max_length=300)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('cur_height', models.FloatField(blank=True, null=True)),
                ('cur_wight', models.FloatField(blank=True, null=True)),
                ('cur_temperature', models.FloatField(blank=True, null=True)),
                ('cur_bood_pressure', models.FloatField(blank=True, null=True)),
                ('cur_heart_rate', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.EmailField(blank=True, default=None, max_length=70, null=True, unique=True)),
                ('specialist', models.CharField(choices=[('Family medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Pediatrician', 'Pediatrician'), ('Obstetricians/gynecologist (OBGYNs)', 'Obstetricians Gynecologist'), ('Cardiologist', 'Cardiologist'), ('Oncologist', 'Oncologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Infectious disease', 'Infectious Disease'), ('Nephrologist', 'Nephrologist'), ('Endocrinologist', 'Endocrinologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Dermatologist', 'Dermatologist'), ('Psychiatrist', 'Psychiatrist'), ('Neurologist', 'Neurologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Surgeon', 'Surgeon'), ('Physician executive', 'Physician Executive')], max_length=50)),
                ('appointment_date', models.DateField(default=None)),
                ('appointment_time', models.TimeField(default=None)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('done', 'Done')], default='waiting', max_length=10)),
                ('note_to_doctor', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('usage', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'medicine')},
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(through='prescribing_management.PrescriptionDetail', to='prescribing_management.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('card_num', models.IntegerField(default='30213124921', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.carddetail')),
                ('invoice', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.invoicedetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.medicinetype'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.medicine'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='medicines',
            field=models.ManyToManyField(through='prescribing_management.InvoiceDetail', to='prescribing_management.medicine'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicedetail',
            unique_together={('invoice', 'medicine')},
        ),
    ]
