# Generated by Django 4.1.2 on 2022-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribing_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
