# Generated by Django 4.1.2 on 2022-11-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribing_management', '0002_remove_invoicedetail_is_paid_invoice_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='CardDetail',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
