# Generated by Django 4.1.2 on 2022-12-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescribing_management', '0003_remove_payment_card_remove_payment_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='blood_pressure',
            new_name='bood_pressure',
        ),
    ]
