# Generated by Django 4.1.2 on 2022-12-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescribing_management', '0004_rename_blood_pressure_patient_bood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescribing_management.doctor'),
        ),
    ]
