# Generated by Django 4.1.2 on 2022-12-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescribing_management', '0005_schedule_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='doctor',
        ),
    ]
